### ISSUE TITLE
Button [Save] is not formatted

### ISSUE THREAD

**Issue by vipeol** [arodu/cakelte#10]
When we execute cake bake all [] -t CakeLte, the forms add and edit into /templates/[]/add and edit the buttons [SAVE] are come without fomatetion.

Thanks..
![image](https://user-images.githubusercontent.com/20286865/104811547-15cad200-57db-11eb-970f-29b54646e25a.png)

**Comment by arodu** [comment]
Hi @vipeol
what version are you using?

in version 0.2, I'm using [bootstrap-ui](https://github.com/FriendsOfCake/bootstrap-ui) to format automatically with bootstrap.
