### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by gooseleggs** [arodu/cakelte#30]
Hello 

I have just created a clean CakePHP 4.3 install, and used composer to install the plugin as detailed by your page.  However, when I enable as per the AppView method, I end up with 

```
syntax error, unexpected 'Helper' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
ROOT/vendor/arodu/cakelte/src/View/Styles/Header.php
Error in: ROOT/vendor/arodu/cakelte/src/View/Styles/Header.php, line 34
```
and the page does not load up now.

Any assistance would be appreciated.

Using CakePHP 4.3.2
PHP: 7.3.29

*UPDATE*
If I comment out the two private variable lines from Header.php and Sidebar.php files, it seems to be working.  Haven't done much more testing, other than load up the debug page a click around

**Comment by gooseleggs** [comment]
OK - looks like it works fine under PHP 8.0.  Under PHP 7 it looks like you might need to change those lines from:

```
    private Helper $_helper;
    private string $_name;
```
to be
```
    private $_helper;
    private $_name;
```

**Comment by arodu** [comment]
Thanks for the help, I'll make that change
