### ISSUE TITLE
Form Class

### ISSUE THREAD

**Issue by yanisasan** [arodu/cakelte#6]
how to configure form-horizontal, because
I have added class class-horizontal but it's still not running

thanks

**Comment by arodu** [comment]
I just uploaded a change where I include the integration with the [bootstrap-ui](https://github.com/FriendsOfCake/bootstrap-ui) plugin, this plugin has everything you need to fully work with bootstrap.

You only have to update to version 0.2.x and you can already use the methods included in the bootrstrap-ui, here it explains how to work with the Horizontal forms https://github.com/FriendsOfCake/bootstrap-ui#horizontal-forms

And thanks to help me
