### ISSUE TITLE
CakeLteHelper could not be found.

### ISSUE THREAD

**Issue by himanshuvora** [arodu/cakelte#68]
I have followed the steps given here, but I am getting this error.

Missing Helper
Cake\View\Exception\MissingHelperException

I couldn't understand following,

- To modify the template you can copy one or all the files within your project
- Page debug

If someone could help me, please share how to resolve this issue.

**Comment by arodu** [comment]
in the src/View/AppView.php you need to execute the command `$this->initializeCakeLte();` there is the command that loads the helper. https://github.com/arodu/cakelte#how-to-use

To copy the elements you need, look for them inside the `vendor/arodu/cakelte/templates` plugin and copy them into your project in `templates/plugin/CakeLte`

For example, if you want to modify the layout you would do the following
```
cp vendor/arodu/cakelte/templates/layout/default.php templates/plugin/CakeLte/layout/default.php
```

About Page Debug, that's just a page to verify that the plugin is working correctly.
