### ISSUE TITLE
CakePHP 5?

### ISSUE THREAD

**Issue by bgrinter** [arodu/cakelte#71]
Will cakelte be updated for CakePHP5?

**Comment by arodu** [comment]
That depends on AdminLTE, when they release a new version, we will update too, thank you!
https://github.com/ColorlibHQ/AdminLTE

**Comment by arodu** [comment]
I will start working on this soon, any help is welcome

**Comment by bgrinter** [comment]
> I will start working on this soon, any help is welcome

not sure I'm clever enough, although very happy to help test in any way

**Comment by arodu** [comment]
version 2.x  released!

https://github.com/arodu/cakelte/releases/tag/v2.0.0
