### ISSUE TITLE
issue with the template

### ISSUE THREAD

**Issue by moumene23** [arodu/cakelte#80]
i used cakelte withe cakephp4 and it was great, but now  with cakephp5 and this new version of cakelte, i have an issue with the template, some help plz
![adminlte5](https://github.com/arodu/cakelte/assets/16051844/c4e79bbe-772e-4413-926a-ef7b2acaa49d)

**Comment by arodu** [comment]
now adminlte is installed separately. Just run the following to create the necessary links
```
bin/cake cakelte install
```

or copy the content of `/vendor/almasaeed2010/adminlte/` into `/webroot/adminlte/`

**Comment by moumene23** [comment]
thank you very much my freind , it works with the copy of the content ... thank u
