### ISSUE TITLE
Unable to add menu items in Sidebar.

### ISSUE THREAD

**Issue by ashishonmobile** [arodu/cakelte#81]
Dear Arodu,

I have followed the steps given in your readme file and I was trying to update the menu items but after adding one more item inside menu.php file inside templates/plugin/CakeLte/templates/element/sidebar/menu.php the item is not displaying in left handside of the menubar.

Please let me know If I am doing anything wrong.

Regards
Ashish

**Comment by arodu** [comment]
the correct route should be `templates/plugin/CakeLte/element/sidebar/menu.php`

please, let me know if there is anything in the readme that is not correct.

**Comment by arodu** [comment]
You can also copy those files with this command `bin/cake cakelte copy_files sidebar`

**Comment by ashishonmobile** [comment]
@arodu I followed your steps but still I am not able to see my menu items.

<img width="1313" alt="Screenshot 2024-04-27 at 6 05 25 PM" src="https://github.com/arodu/cakelte/assets/8134811/f43e2159-da37-4b8e-8af5-8406f8153306">
Please find the attached screen shot.

**Comment by arodu** [comment]
this is so weird, the way you have it it should work
By adding the menu file with that structure it should replace the one in the plugin, that is something that cakephp itself does
Show me your AppView file, let's see how you are loading the templates, what version are you using?
do you have skype or telegram?

**Comment by ashishonmobile** [comment]
I just sent a message to your skype id.

**Comment by arodu** [comment]
you're using the same array key for both menu items `simpleLink`.. just changes it.
let me know, if works for you

**Comment by ashishonmobile** [comment]
Yes it worked.
